[package]
name = "stylua_wasynth"
version = "0.1.0"
edition = "2021"

[dependencies]
stylua = { version = "0.20.0", default-features = false, features = ["luau"] }

[profile.release]
lto = true
codegen-units = 1